name: Build

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install python package
      run: |
        pip install pip==20.2.4
        pip install -r requirements_dev.txt
    - name: Build doc
      run: |
        make github
    - name: Publish doc
      uses: EndBug/add-and-commit@v7
      with:
        add: 'docs'
        default_author: github_actions
